name: 'HelmWave'
description: 'Deploy with helmwave'
runs:
  using: 'docker'
  inputs:
    version:
      description: 'helmwave version'
      required: false
      default: 'latest'
    arg:
      description: 'helmwave first arg'
      required: false
      default: 'deploy'
    image:
      description: 'helmwave image'
      required: false
      default: 'diamon/helmwave'

  image: 'docker://'${{ inputs.image.value }}':'${{ inputs.version.value }}
  args:
    - ${{ inputs.arg.value }}
