name: Test plan

on:
  push:

jobs:
  helmwave:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        env:
          HELMWAVE_TAGS: "test"
        with:
          arg: help